# Utiliser l'image Nginx officielle
FROM nginx:alpine

# Copier le contenu du dossier frontend dans le répertoire par défaut de Nginx
COPY . /usr/share/nginx/html

# Exposer le port 80 pour que l'application soit accessible
EXPOSE 80
